### ISSUE TITLE
Lepton Isolation 

### ISSUE THREAD

**Issue by dhkim81** [vallot/CATTools#71] opened 2015-02-03 17:09 UTC
Dear Members.

I received a new 'catTuple_790.root' file.
Opened and check variable plots with Dr.Goh
We found strange Iso files( please refer to plots below )

If you know or have information about Iso plots, please tell us.

-Dong-

![chargedhadroniso](https://cloud.githubusercontent.com/assets/6439809/6024901/f9d221de-abce-11e4-9cae-a74c505502ce.png)
![neutralhadroniso](https://cloud.githubusercontent.com/assets/6439809/6024902/f9d47236-abce-11e4-9fe8-bea4ac4c0ee4.png)
![photoniso](https://cloud.githubusercontent.com/assets/6439809/6024904/f9d8c4e4-abce-11e4-89ad-66ff43940837.png)
![puchargedhadroniso](https://cloud.githubusercontent.com/assets/6439809/6024903/f9d507f0-abce-11e4-97f3-6aa89c82b507.png)

**Comment by jshlee** [comment] 2015-02-03 17:40
Hi Donghyun,

The iso for 0.3 is not filled because they are not present in miniAODs.
Can you use 0.4 for now.

Cheers,
Jason.

On 3 Feb 2015, at 6:09 pm, DongHyun Kim <notifications@github.com<mailto:notifications@github.com>> wrote:

Dear Members.

I received a new 'catTuple_790.root' file.
Opened and check variable plots with Dr.Goh
We found strange Iso files( please refer to plots below )

If you know or have information about Iso plots, please tell us.

-Dong-

[chargedhadroniso]https://cloud.githubusercontent.com/assets/6439809/6024901/f9d221de-abce-11e4-9cae-a74c505502ce.png
[neutralhadroniso]https://cloud.githubusercontent.com/assets/6439809/6024902/f9d47236-abce-11e4-9fe8-bea4ac4c0ee4.png
[photoniso]https://cloud.githubusercontent.com/assets/6439809/6024904/f9d8c4e4-abce-11e4-89ad-66ff43940837.png
[puchargedhadroniso]https://cloud.githubusercontent.com/assets/6439809/6024903/f9d507f0-abce-11e4-97f3-6aa89c82b507.png

**Comment by jshlee** [comment] 2015-02-03 19:07
Hi Donghyun,

I don’t know why the ntuple you have is not working…
Can you try one from our latest production which are located at Kisti.

/cms/data/xrd/store/user/geonmo/cat700_phy14_tw_2025_miniaod
/cms/data/xrd/store/user/geonmo/cat700_phy14_dy_2025_miniaod
/cms/data/xrd/store/user/geonmo/cat700_phy14_tbw_2025_miniaod
/cms/data/xrd/store/user/geonmo/cat700_phy14_ttbar_2025_miniaod
/cms/data/xrd/store/user/geonmo/cat700_phy14_wj_2025_miniaod

/cms/data/xrd/store/user/youn/cat700_phy14_tw_2025_aod
/cms/data/xrd/store/user/youn/cat700_phy14_dy_2025_aod
/cms/data/xrd/store/user/youn/cat700_phy14_tbw_2025_aod
/cms/data/xrd/store/user/youn/cat700_phy14_wj_2025_aod
/cms/data/xrd/store/user/youn/cat700_phy14_ttbar_2025_aod

Cheers,
Jason

On 3 Feb 2015, at 6:40 pm, Jason Lee <jason.lee@cern.ch<mailto:jason.lee@cern.ch>> wrote:

Hi Donghyun,

The iso for 0.3 is not filled because they are not present in miniAODs.
Can you use 0.4 for now.

Cheers,
Jason.

On 3 Feb 2015, at 6:09 pm, DongHyun Kim <notifications@github.com<mailto:notifications@github.com>> wrote:

Dear Members.

I received a new 'catTuple_790.root' file.
Opened and check variable plots with Dr.Goh
We found strange Iso files( please refer to plots below )

If you know or have information about Iso plots, please tell us.

-Dong-

[chargedhadroniso]https://cloud.githubusercontent.com/assets/6439809/6024901/f9d221de-abce-11e4-9cae-a74c505502ce.png
[neutralhadroniso]https://cloud.githubusercontent.com/assets/6439809/6024902/f9d47236-abce-11e4-9fe8-bea4ac4c0ee4.png
[photoniso]https://cloud.githubusercontent.com/assets/6439809/6024904/f9d8c4e4-abce-11e4-89ad-66ff43940837.png
[puchargedhadroniso]https://cloud.githubusercontent.com/assets/6439809/6024903/f9d507f0-abce-11e4-97f3-6aa89c82b507.png

**Comment by dhkim81** [comment] 2015-02-03 20:14
Dear Jason.

thanks for your comment.
I used 0.4
And then, i will try to data on the Kisti.
Thanks

regards,
Dong

**Comment by dhkim81** [comment] 2015-02-03 20:15
Thanks
I will try this data

regards,
Dong

**Comment by dhkim81** [comment] 2015-02-03 20:42
Dear Jason.

This plot used 0.4.
Thanks

regards,
Dong

**Comment by jhgoh** [comment] 2015-02-03 22:52
The root file was copied from kisti at some point, but I don't remember what it was actually.
Maybe it was from the previous production campaign, let me check once again.

**Comment by jhgoh** [comment] 2015-02-03 23:18
It seems something strange happened with Donghyun's configuration.
With my configurations, isolation distribution looks quite reasonable.

BTW, He was opening new catTuple with old CATTools environment (before merging new DataFormats). Could this corrupt event content? I don't know how this can happen but just for a possibility.

@dhkim81 could you open the same file after clear setup?

**Comment by jshlee** [comment] 2015-02-03 23:40
I don’t think it can effect the event content. Accessing the variables through the classes with an old format might.
Here is the distributions I see for the samples made by prod 700 without cmsenv setup.

On 4 Feb 2015, at 12:18 am, Junghwan John Goh <notifications@github.com<mailto:notifications@github.com>> wrote:

It seems something strange happened with Donghyun's configuration.
He was opening new catTuple with old CATTools environment (before merging new DataFormats). Could this corrupt event content? I don't know how this can happen but just for a possibility.

@dhkim81https://github.com/dhkim81 could you open the same file after clear setup?

**Comment by jhgoh** [comment] 2015-02-03 23:52
Missing attachment maybe, but from the experiences, I believe we must see same distributions with and without FWLite.

I wanna leave this issue 2B opened until this afternoon. There could be some hints for corruption.

**Comment by jshlee** [comment] 2015-02-04 00:13
I attached them as eps, I guess git can’t handle them.
Here are the pdfs.
Can you let us know where you got this file from?
Also, does Donghyun see the correct distribution without FWLite?

On 4 Feb 2015, at 12:52 am, Junghwan John Goh <notifications@github.com<mailto:notifications@github.com>> wrote:

Missing attachment maybe, but from the experiences, I believe we must see same distributions with and without FWLite.

I wanna leave this issue 2B opened until this afternoon. There could be some hints for corruption.

**Comment by jhgoh** [comment] 2015-02-04 00:27
Still no image, but doesn't  matter at all.
Regarding on the root file, I directly copied that file from kisti, xrd cp, in my desktop in B588 (cmskr-002-00:/store1/jhgoh/catTuple_790.root you can scp with your lxplus account.)
Dong scp-ed it from my desktop.

I cannot reproduce Dong's problem. Nothing strange to me.
But at the moment when I checked plots with him with his account/env at lxplus, isolation values were complete mess. 

Weird, huh?

**Comment by jshlee** [comment] 2015-02-04 00:30
That is weird... Which commit was he using?

On 4 Feb 2015, at 1:27 am, Junghwan John Goh <notifications@github.com<mailto:notifications@github.com>> wrote:

Still no image, but doesn't matter at all.
Regarding on the root file, I directly copied that file from kisti, xrd cp, in my desktop in B588 (cmskr-002-00:/store1/jhgoh/catTuple_790.root you can scp with your lxplus account.)
Dong scp-ed it from my desktop.

I cannot reproduce Dong's problem. Nothing strange to me.
But at the moment when I checked plots with him with his account/env at lxplus, isolation values were complete mess.

Weird, huh?

**Comment by jhgoh** [comment] 2015-02-04 16:34
So, we can conclude this is due to wrong version of library in Dong's working directory.
I'm closing this issue.

**Closed as completed by jhgoh** 2015-02-04 16:34 UTC
