### ISSUE TITLE
To check that the secondary vertex collection can be embeded.

### ISSUE THREAD

**Issue by geonmo** [vallot/CATTools#311] opened 2015-11-27 09:41 UTC
### Motivation
- For J/psi analysis,  I want to embed the secondary vertex collection to official CATTools.
  However, in most case, the secondary vertiecs(below SV) have too big size to put the ntuple.
  So, we need to check their size, precut with least loss and input collection to reconstruct to SV.
### CheckPoint ( Higher is more important. )
1. Size           : small size is mandatory for official production.
2. Efficiency  : can be produced using miniAOD.
3. Availability : can be produced using miniAOD.
4. Time          : too many time cause to fail grid job.
### Methods
1. <strike>Conventional Lepton+Lepton reconstruction</strike> : Obsoleted by 8TeV Analysis due to too small statistics
2. Lepton + general tracks( Now, patMuons + generalTracks )
   - GeneralTracks can be available on AOD samples.
   - Already porting to CMSSW 7XY.
3. MiniAOD's SlimmedSecondaryVertices
   - Available with miniAOD.
   - It did not produced for j/psi. So, I need to check about efficiency of J/psi
4. packedPFCandidates + packedPFCandidates
   - Available with miniAOD.
   - It also need to check of J/psi efficiency
### Time Table( Higher is first )
1. As soon as possible to porting (3), (4) reco methods as CATTools producer.
2. Compare the size between 2,3 and4
3. Compare the efficiency between 2,3 and4

**Comment by geonmo** [comment] 2015-11-27 09:50
#### Quick & Dirty results
-  Size of method(2)

``` bash
recoGenParticles_prunedGenParticles__CAT. 3950.91 781.356
catSecVertexV2s_catSecVertexsV2__CAT. 4375.59 1384.51
catSecVertexs_catSecVertexs__CAT. 131.93 25.799
```
- Maybe, catSecVertex**V2** **can not be used** for cat ntuple without strong precut. ( x4 catJets ) :boom:

**Comment by jhgoh** [comment] 2015-11-27 12:09
what is catSecVertexsV2?

**Comment by jshlee** [comment] 2015-11-27 12:39
i think catSecVertexsV2 is the updated one

**Comment by jshlee** [comment] 2015-11-27 12:40
@geonmo use the cern cuts for now
and also add in D\* candidates

**Comment by geonmo** [comment] 2015-11-27 12:59
@jhgoh catSecVertexV2 means 2nd methods.(Lepton + generalTracks)
I will also make V3 and V4 for method 3 and 4.

**Comment by geonmo** [comment] 2015-11-27 13:00
Of course, it will not push to official. These are made to compare J/psi candidates for each modules.

**Comment by jhgoh** [comment] 2015-11-27 16:21
![screen shot 2015-11-28 at 1 19 52 am](https://cloud.githubusercontent.com/assets/4388926/11445266/2fc4757e-956e-11e5-9628-b1fa530a2ec3.png)

To reproduce this,

``` bash
root -l root://eoscms//store/relval/CMSSW_7_4_15/RelValTTbar_13/MINIAODSIM/PU25ns_74X_mcRun2_asymptotic_v2-v1/00000/0253820F-4772-E511-ADD3
```

and

``` cpp
Events->SetAlias("svp4", "recoVertexCompositePtrCandidates_slimmedSecondaryVertices__RECO.obj.m_state.p4Polar_.fCoordinates");
Events->SetAlias("svvtx", "recoVertexCompositePtrCandidates_slimmedSecondaryVertices__RECO.obj.m_state.vertex_.fCoordinates");
Events->Draw("sqrt(svvtx.fX*svvtx.fX+svvtx.fY*svvtx.fY)/svp4.fPt*svp4.fM>>h(100,0,0.2)");
```

Gives lxy distribution quickly.

**Comment by jhgoh** [comment] 2015-11-27 16:23
And the mass distribution

![screen shot 2015-11-28 at 1 23 44 am](https://cloud.githubusercontent.com/assets/4388926/11445338/b0899888-956e-11e5-91e8-2ff0e8fab100.png)

**Comment by geonmo** [comment] 2015-11-30 15:39
### Quick & Dirty result(2)
- I made other 2 producer about miniaod's secvtx and packedPFCandidates.
- This is a data size for each modules. ( No pre-cut. )

``` bash
[geonmo@kcms01 src]$ cat size_v4.txt  | sort -n | grep catSecVertex
catSecVertexV2s_catSecVertexsV2__CAT. 40026.6 12126.9  # lepton + generalTracks
catSecVertexV2s_catSecVertexsV3__CAT. 462.159 372.464  # miniAOD's catSecVtx
catSecVertexV2s_catSecVertexsV4__CAT. 557.159 421.565  # pfCandidates + pfCandidates
catSecVertexs_catSecVertexs__CAT. 404.681 323.812
```

```
  *  On this result, (No precut) catSecVertex collections size are located from 1/2 to 2/3 of catJets size.
  * V2 is too large to embeded.
```
- I will upload about mass plots and efficiency of catSecVtx over genJpsi(pdgId == 443).

**Comment by jshlee** [comment] 2015-11-30 15:46
Hi @geonmo,
Have a read of the analysis note from 8 tev and put all the required variables into https://github.com/vallot/CATTools/blob/cat75x/DataFormats/interface/SecVertex.h

and then put some cuts to reduce the number of SecVertexes. 
I dont think its worth keeping general tracks and pf candidates

**Comment by jhgoh** [comment] 2015-11-30 16:47
I think he is not storing general tracks nor pf cands of course. He is trying to estimate effect of chosing different input objects to build catSecVertices.

Summarizing up:
- Lepton + generalTracks - high eff, high fake, large event size, AOD/RECO only
- catSecVtx - small size, easy, ready-made sec vtxs, eff to be understood, MiniAOD as is
- pfCand+pfCand - moderate size, eff to be understood, works with MiniAOD (@geonmo finished implementation right?)

**Comment by geonmo** [comment] 2015-12-01 09:55
@jshlee @jhgoh hello, all. I will draw the efficiency plots of [reco Jpsi] over [gen Jpsi]. Then, I will determine best catJpsi producer. After this job, I will put all variable to "new" SecVtx producer on CATTools.

**Comment by geonmo** [comment] 2015-12-02 14:43
### Quick and Dirty (3)

#### Result
- Sample : J/Psi to mu Mu 1000 events
- CMSSW_7_4_15 + method 2,3,4 producers
- Below is efficiency plots,
  ![eff_try1](https://cloud.githubusercontent.com/assets/4969463/11533515/797f44d6-994d-11e5-9e7e-5d06de6651d3.png)
- Method3 can not make the secVtx from AODSIM samples.(If I did not take a misktake,)
- Method4(Pf + Pf) is not better than original one(Method1).
  - Maybe, it is come from a cut about abs(pdgId())==11 or 13.

#### Plan
- To find a bug for method3.
- To modify the method4 with pdgId cut for 1 leg only.

**Comment by geonmo** [comment] 2015-12-02 14:50
I forgot a matching algorithm.
- dR < 0.15
- dPt < 5%
- Only choose closest(small dR) reco candidate.( avoid to duplicate.)

**Comment by jhgoh** [comment] 2015-12-02 15:01
1. Did you apply acceptance cut on gen level jpsi's?
2. Can you add number of jpsi candidate plots (without matching)?
3. Method3 must be OK on MiniAODSIM.

**Comment by geonmo** [comment] 2015-12-02 15:16
@jhgoh 1. I did not apply that. Ok, I will apply |eta<2.4| cut for genJpsi.
2. Can I upload about avergae of J/psi candidates?
3. Ok, I skip to find a bug for method3 before using miniAOD sample.

**Comment by geonmo** [comment] 2015-12-02 15:20
@jhgoh @jshlee Did you know how to solve below error?

``` bash
A std::exception was thrown.
BasicSingleVertexState::could not invert weight matrix
```

I faced this error after modifying **method 4** to use pf(lepton pdgId) + pf(all).

**Comment by jshlee** [comment] 2015-12-02 15:21
reject these candidates

**Comment by jhgoh** [comment] 2015-12-02 15:34
If jpsi multiplicity is ~1 then you can just postpone to apply complicated matching cuts. I was just wondering about unnecessary loss during gen-reco matching.

**Comment by jshlee** [comment] 2015-12-02 22:09
@geonmo, this could be due to neutral pf candidates.
check that the pf has charge

**Comment by geonmo** [comment] 2015-12-03 05:33
@jshlee Thanks, Jason. It works. Almost errors are solved. Some errors are remain but I by-pass to use try-catch handle.

**Comment by geonmo** [comment] 2015-12-03 06:23
@jhgoh @jshlee Hello, This is an updates today.

### Quick and dirty(4)

#### Efficiency plots

![eff_try4](https://cloud.githubusercontent.com/assets/4969463/11553229/05271cac-99d0-11e5-9a3f-c08617652e85.png)

#### Average of J/psi multiplicity

![avr_jpsi](https://cloud.githubusercontent.com/assets/4969463/11553299/b3cf3398-99d0-11e5-8548-b5a7d738d8dc.png)
- Method(4)'s efficiency is recovered. Now, this method's efficiency is 86.3%. It is higher than original method but it is worse than lepton+generalTracks.
- Average of method(2) is about 11. (GenJpsi is only 1 existed for each events.)
- Method(4)'s average is about 2.5.
- As this result, method(4) is preferable to embed for official CAT ntuple.

**Comment by geonmo** [comment] 2015-12-08 15:19
After merge and add some feature, I checked the efficiency for several cases.
- New case 
  - method(4-0) : pfCandidate(pdgId==11,13) && pfCandidate(pdgId==11,13))
  - method(4-1) : pfCandidate(pdgId==11,13) && pfCandidate(any pdgId))  (Previous : method4, default)
  - method(4-2) : pfCandidate(any pdgId) && pfCandidate(any pdgId))

Here is efficiency and fake result,

### Quick and dirty(5)

#### Efficiency

![eff_comparison_v5](https://cloud.githubusercontent.com/assets/4969463/11659076/aee011d0-9e09-11e5-9afb-bc3a58957716.png)
- No efficiency gain on method(4-2) [all pfcandidates pair if they are opposite sign ]

#### Fake rate

![multiplicity_comparison](https://cloud.githubusercontent.com/assets/4969463/11659118/e08eb498-9e09-11e5-9c38-d96c1baac16d.png)
- Too many fake for method(4-2)[ x10 lepton+ generalTracks]

#### Result
- The method(4-2) is worst on j/psi to mumu sample. 
- For D\* analysis, some tight cut is required.

**Comment by geonmo** [comment] 2015-12-08 15:20
I forgot that event size each modules.

``` bash
catSecVertexs_catSecVertexsV2__CAT. 3772.3 1188.51
catSecVertexs_catSecVertexsV3__CAT. 146.06 28.658
catSecVertexs_catSecVertexsV40__CAT. 430.595 132.88
catSecVertexs_catSecVertexsV41__CAT. 975.228 319.919
catSecVertexs_catSecVertexsV42__CAT. 35851.1 10802.5
catSecVertexs_catSecVertexs__CAT. 441.334 135.844
```

**Comment by jhgoh** [comment] 2015-12-10 18:44
The efficiency can be under-estimated if you don't apply acceptance cut on the Jpsi decay products. The acceptance cut may vary depending on your physics interests.
I expect jpsi's in your analysis are highly boosted since it is one of decay products of top quark, mTop >> mJpsi - then pfLepton+pfLepton will be efficient enough to cover your signal box.

**Comment by jhgoh** [comment] 2015-12-29 08:12
Are there any progress (or plan) on this issue?

**Comment by jshlee** [comment] 2015-12-29 23:18
isnt this already merged?

**Comment by jshlee** [comment] 2016-01-04 10:46
@geonmo do you want to close this?

**Comment by jhgoh** [comment] 2016-01-18 17:11
@geonmo is this merged in the central production?

**Comment by geonmo** [comment] 2016-01-18 17:32
@jhgoh @jshlee Hello, everyone. I am sorry about late reply. I am working different job. I can not handle this issue for this production. Please, ignore "seconday vertex collection" for this production. I will make a private one for my analysis for a while.

**Comment by geonmo** [comment] 2016-02-04 11:54
On #403, I calculated MiniAOD's nature SecVtx's efficiency.

It is not better than v41. So, I will fix the v41 to default.

![p7](https://cloud.githubusercontent.com/assets/4969463/12814129/13914074-cb80-11e5-93b0-05742122c7b0.png)

**Comment by jshlee** [comment] 2016-02-04 13:46
can we close this issue?

**Comment by geonmo** [comment] 2016-02-04 13:47
Yep!

**Closed as completed** 2016-02-04 15:41 UTC
Labels: analysis-tools
